---
title: "Justifications of Harm in Political Manifestos"
author: Morgan Ballesteros
format: pdf
echo: false
---

# Justifications of Harm in Political Manifestos

The theory of dyadic morality suggests that judgments of harm give moral valence to
relationships between an intentional agent and vulnerable patient (Schein & Gray, 2018). That
is, dyadic morality predicts that if one were to see someone (i.e., an agent) intentionally
harming another person (i.e., a vulnerable patient), one would judge that this action (i.e.,
the harming of another person) is immoral or morally wrong. Furthermore, social interactions
are composed of moral norms as mutually agreed upon rules as to how citizens ought to behave.
Although moral norms (e.g., do not murder) are meant to keep people from damaging others,
some justify norm violations — and harm — in pursuit of a goal (e.g., political
assassinations), whereas others never condone violence to induce change. Understanding what
differentiates violent and non-violent agents is therefore useful in protecting against
harmful acts. One source that marks such differences is the political manifesto (i.e., “a
written statement declaring publicly the intentions, motives, or views of its issuer”;
Merriam-Webster, n.d.). The current study will target differences in linguistic indicators of
justifications of harm and integrative complexity between violence-condoning and non-violent
manifestos.

Research on linguistic markers of political violence follows the growing number of far-right
manifestos published online prior to terrorist attacks (Capelos et al., 2025; Ebner et al.,
2025). Some of these studies evaluate manifestos through the fusion-plus-threat model of
violent extremism (Whitehouse, 2018), which predicts that individuals who lump their personal
and group identities together will be more likely to self-sacrifice for their group.
Associated linguistic work suggests that words indicating identity fusion, group threat, and
violence-condoning norms — including justifications of violence — are correlated with 
terrorism (Ebner et al., 2024; Ebner et al., 2025). While the existing literature grounds the
importance of justificatory rhetoric in predicting terrorism, harm has not yet been examined 
as central to moral judgment despite its importance in some theories of moral judgment (e.g.,
the theory of dyadic morality). The present study serves as a real-world case on how emotion 
and reason interact to produce the judgments and justifications necessary for enacting harm. 
Connecting the political manifesto and moral judgment literatures might enlighten respective 
research as to (a) how moral reasoning implicates justification in manifestos and (b) how 
justification operates in the moral reasoning process, each of which could have policy 
implications.

Integrative Complexity is a linguistic measure of cognitive complexity composed of two primary components: (a) Differentiation and (b) Integration (Suedfeld et al., 1992). Differentiation indicates how many perspectives one accounts for; Integration indicates the extent to which those differentiated perspectives are synthesized. A useful example is an argumentative essay, which, if it is complex, recognizes a variety of possible arguments for or against some claim, and synthesizes those arguments into one ultimate argument, using parts of each subsidiary argument. Integrative complexity shows a robust relationship with political violence (Suedfeld, 2010). However, research using the construct as a predictor of political violence has largely focused on political leaders in respect to events like war and international crises (Suedfeld, 2010). To my knowledge, no study to date has directly linked the integrative complexity of political manifestos with justifications of political violence. Considering the measure’s long-standing precedent in predicting political events, integrating integrative complexity into the manifesto literature could help identify the factors that distinguish between merely violent rhetoric and rhetoric that induces violence, thereby affording greater predictability through an aggregation of said factors.

# Current Study

The current study contributes to research seeking to identify differences between violent and non-violent political agents through an evaluation of political manifestos in two new ways: (a) by focusing a qualitative analysis on rhetoric about harm as designating moral valence by the theory of dyadic morality and (b) by scoring manifestos on integrative complexity. I seek to aid in answering three related questions: (a) do justifications of harm correspond to changes in individual moral norms?; (b) does integrative complexity predict whether a manifesto will result in violence versus non-violence?; and (c) does integrative complexity predict both temporally near and far instances of violence in relation to political manifestos? I predict that (a) changes in moral norms — as exemplified in the agents’ writings — and subsequent justification of increasingly harmful acts will be associated with a higher likelihood of violence, (b) lower levels of integrative complexity in political manifestos will predict higher likelihoods of violence, and (c) a decrease in integrative complexity will be associated with an individual coming to believe that harm is justified in pursuit of their political goals.

# Method

## Manifesto Selection

  This study must include manifestos that can be placed into one of three categories; (a) violent self-sacrificial, (b) ideologically extreme, and (c) moderate (Ebner et al., 2025). It must also afford longitudinal analysis. Thus, this selection will include not only one-off manifestos already analyzed in the aforementioned literature (e.g.,  Anders Behring Breivik’s Manifesto of the Norway Attacks, 2011; Marx & Engels Manifesto of the Communist Party, 1848), but also sets of writings of individual authors across time (e.g., selections of Vladimir Lenin’s letters). Materials will include ten manifestos for each of the aforementioned categories, and three longitudinal sets of writings for each category. Including the 15 manifestos previously analyzed in the literature brings the study to a categorical count as follows: (a) nine violent self-sacrificial texts, (b) three ideologically extreme texts, and (c) 3 moderate texts. Each of these texts are one-off samples. To fill out the rest of the ten one-off samples for each category, manifestos will be selected according to their place on the political spectrum (i.e., left to right political platforms), individual actor-author texts versus platform-representative texts, and length in order to match each category along these factors. The same factors will be considered in choosing longitudinal samples, ideally including qualitatively matching samples across categories.
  
## Measures

	Linguistic Indicators. Ebner et al. (2025) supplies a list of words that indicate justifications of violence and, as a higher-order category of linguistic markers, violence condoning norms. The current study will use the set of words indicating violence condoning norms with minor alterations. First, indicators like “need for jihaad” (Ebner et al., 2025) will be replaced with relevant phrasing (e.g., need for war; need for revolution). Second, specific indicators of talk about harm in dyadic morality (e.g., harm, damage, agent, patient, intentional) will be added to the list of indicators.
	Automated Integrative Complexity. Hand-scoring integrative complexity is an involved process requiring multiple scorers and often hours of work per scored material. In light of time and manpower limitations, this study will instead use automated integrative complexity (Conway et al., 2014) to score materials, a measure that uses linguistic markers of differentiation and integration to construct an automated account of integrative complexity. While automated integrative complexity does not correlate perfectly with hand scores (document-level correlation of .82, paragraph-level correlation of .46, Conway et al., 2020), it is an increasingly validated measure in its own right and often used as an efficient and effective replacement for hand scoring. This study will use the document-level scores for all analyses.
	Violence. Previously analyzed manifestos are easily delineated as to whether they cause violence; some manifestos precede lone-actor attacks by their author, the other manifestos did not precede violence enacted by their author. The present study maintains this distinction. However, it also includes platform-based violence by identifying institutional violence in direct causal relationship with the philosophies put forward by corresponding manifestos. For example, a manifesto by a political leader that accompanies a war (e.g., the Russian Imperial Manifesto of 1914 by Tzar Nicholas II announcing Russia’s entry into World War One; Golder, 1927) would be counted as violent; a manifesto espoused by a political leader that does not accompany institutional violence by that leader’s institution (e.g., John F. Kennedy’s Ich bin ein Berliner) would be counted as non-violent.
	
## Analyses

	Following Ebner et al. (2024), I will measure the prevalence of various categories of linguistic markers indicating violence condoning norms (i.e., justification of violence, martyrdom narrative, hopelessness of alternatives, calls to violence) and harm as a percentage of occurrence relative to total sentence count. These prevalence rates will be compared across manifesto categories (i.e., violent versus non-violent, extreme versus non-extreme) to replicate Ebner et al. (2024) results suggesting that justification of violence is a significant predictor between categories. I will create .zip files for each selected manifesto and run them through automated integrative complexity, which will give scores for integrative complexity, differentiation, and integration. These scores will be compared in the same manner as prevalence rates. I will also run regression analyses for longitudinal manifesto sets in order to understand the effect changes in integrative complexity have on likelihood of violence. I will repeat these analyses for linguistic markers of harm on said longitudinal sets.
	
# Discussion

	In line with my aforementioned hypotheses, I predict that (a) greater prevalence of linguistic indicators of harm will be associated with higher a likelihood of political violence, (b) lower integrative complexity, differentiation, and integration scores will be associated with a higher likelihood of political violence, and (c) decreasing integrative complexity, differentiation, and integration scores longitudinally will be associated with higher likelihoods of political violence. The proposed study adds to the ongoing literature on linguistic markers of political violence and on the predictive power of integrative complexity for major political events. New to the linguistic marker literature is the inclusion of longitudinal data, which is useful in that many of the far-right manifestos studied in the literature are posted online just prior to or after acts of violence, meaning that they are limited in their capacity to serve as practically useful predictors of terrorism because those who protect against said violence cannot find and act against such terrorism quickly enough. Integrative complexity is robust in its long-term predictive power, meaning that an analysis of political platform manifestos can be tracked well before violence on their account occurs. Politically oriented research using integrative complexity has not yet looked at lone actor terrorism to my knowledge, instead focusing on political leaders’ textual data for its greater accessibility. However, if evaluating manifestos that are published shortly before acts of political violence and manifestos that ground political platforms predict violence, both in the long- and short-term, then integrative complexity can become a powerful tool in tracking and stopping what are increasingly prevalent lone actor violent acts. This study thus aims to help public safety policy makers understand the precursors of political violence and intervene before tragedy strikes.
	
## Limitations

	The availability of political manifestos is the primary limitation of the proposed study. Relevant prior literature on linguistic markers in political manifestos (i.e., Capelos et al., 2025; Ebner et al., 2024; Ebner et al., 2025) share sets of either six or 15 manifestos, citing issues including “the limited availability of terrorist manifestos, access restrictions to such documents, as well as researcher time considerations” (Ebner et al., 2024). The current study delimits time constraints by using R to automate prevalence rates and automated integrative complexity to measure integrative complexity, but manifesto accessibility remains an issue. To gain statistical power, I will not limit data selection to terrorist manifestos, but will also include writings that contributed to the development of political platforms (i.e., The Manifesto of the Communist Party, which is used in prior literature, and Vladimir Lenin’s What Is To Be Done?, a novel addition). Thus, access to such works through sites like the Marxists Internet Archive provides a wide range of writings to choose from, both as select instances and as pieces of a longitudinal series.


# References

Capelos, T., DaVisio, K., Salmela, M. (2025). “Today I Die like Jesus Christ”: An Analysis of Ressentiment in Perceptions, Motivations and Justifications of Violent Extremist Manifestos. Terrorism and Political Violence, 37(8), 1031-1047. https://doi.org/10.1080/09546553.2024.2379043
Conway, L. G., III, Conway, K. R. (2016). User Instructions. Automated Integrative Complexity. Instructions – Automated Integrative Complexity (autoic.org) 
Conway, L. G., Conway, K. R., Gornick, L. J., & Houck, S. C. (2014). Automated Integrative Complexity. Political Psychology, 35(5), 603–624. https://doi.org/10.1111/pops.12021 
Conway, L. G., Conway, K. R., & Houck, S. C. (2020). Validating automated integrative complexity: Natural language processing and the Donald Trump Test. Journal of Social and Political Psychology, 8(2), 504–524. https://doi.org/10.5964/jspp.v8i2.1307 
Ebner, J., Kavanagh, C., & Whitehouse, H. (2024). Measuring socio-psychological drivers of extreme violence in online terrorist manifestos: an alternative linguistic risk assessment model. Journal of Policing, Intelligence and Counter Terrorism, 19(2), 125-143. https://doi.org/10.1080/18335330.2023.2246982
 Ebner, J., Kavanagh, C., & Whitehouse, H. (2025). Is there a language of terrorists: A comparative manifesto analysis. Studies in Conflict and Terrorism, 48(6), 601-628.  DOI: 10.1080/1057610X.2022.2109244
Merriam-Webster. (n.d.). Manifesto. In Merriam-Webster.com dictionary. Retrieved January 22, 2026, from https://www.merriam-webster.com/dictionary/manifesto
Golder, F. (927). Documents of Russian History, 1914-1917, pp. 29-30, citing Riech, no. 193, August 9, 1914.
Schein, C., Gray, K. (2018). The Theory of Dyadic Morality: Reinventing moral judgment by redefining harm. Personality and Social Psychology Review, 22(1), 32-70. DOI: 10.1177/1088868317695288
Suedfeld, P. (2010). The cognitive processing of politics and politicians: Archival studies of conceptual and integrative complexity. Journal of Personality, 78(6), 1669-1702. 
Suedfeld, P., Tetlock, P. E., & Streufert, S. (1992). Conceptual/integrative complexity. In Cambridge University Press eBooks (pp. 393–400). https://doi.org/10.1017/cbo9780511527937.028 
 Whitehouse, H. (2018) Dying for the group: Towards a general theory of extreme self-sacrifice. Behavioral and Brain Sciences, 41, e192: 1–62. doi:10.1017/ S0140525X18000249

